### ISSUE TITLE
[BUG] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by KubaTMofficial** [Osaxely/mc_addons_manager#72] opened 2021-04-11 15:14 UTC
**Describe the bug**
When importing mcaddon I am getting error "Object reference not set to an instance of an object"

**To Reproduce**
1. Select random mcaddon (works on PC/tested on PC)

**Expected behavior**
Addon should import successfully.

**Screenshots (Optional)**
![1618153979386405699457124985418](https://user-images.githubusercontent.com/47297843/114309916-34deb480-9ae9-11eb-83d8-63e9766dc54a.jpg)

**Desktop (Optional):**
 - OS: Xbox One S
 - Version 10.0.19041.7338

**Additional context**
Some addons work some not and that's weird. It happens sometimes on behavior packs too

**Comment by Osaxely** [comment] 2021-04-11 15:52
Hello, could you please send me one pack that have this issue ? Thanks !

**Comment by Osaxely** [comment] 2021-04-12 10:15
Hello, thank you very much for your report and clarification about happening on behavior packs :)
I may have found the issue, and explaining it here.
On behavior packs, there is sometimes a folder called "bridge" which allow the pack to have plugins, and the issue is that plugins use a file called "manifest.json", which is the same as the manifest inside the pack, but a different structure. MC Addons Manager tries to get the pack type from this file while importing, but it can't because the structure is too different.

I am planning to solve that issue by two ways : Ignore "bridge" folder, or simply check if the file can be parsed.

**Comment by Osaxely** [comment] 2021-04-13 20:55
Hello @KubaTMofficial The issue was fixed on the update that got released a few hours ago, please check and let me know how it goes! :)

**Comment by Osaxely** [comment] 2021-05-01 18:18
Closing because this issue is fixed.

**Closed** 2021-05-01 18:19 UTC
Labels: Bug, FIXED
